from io import BytesIO
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet


def generate_player_report_pdf(
    profile,
    strengths,
    improvements,
    similar_players,
    scout_summary,
):
    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)
    styles = getSampleStyleSheet()

    content = []

    content.append(Paragraph("MAPLE SCOUTING REPORT", styles["Title"]))
    content.append(Spacer(1, 12))

    content.append(Paragraph("Player Information", styles["Heading2"]))

    for key, value in profile.items():
        content.append(
            Paragraph(f"<b>{key}</b>: {value}", styles["BodyText"])
        )

    content.append(Spacer(1, 10))

    content.append(Paragraph("Strengths", styles["Heading2"]))
    for item in strengths:
        content.append(
            Paragraph(f"• {item}", styles["BodyText"])
        )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph("Areas for Improvement", styles["Heading2"])
    )

    for item in improvements:
        content.append(
            Paragraph(f"• {item}", styles["BodyText"])
        )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph("Similar Players", styles["Heading2"])
    )

    for player in similar_players:
        content.append(
            Paragraph(f"• {player}", styles["BodyText"])
        )

    content.append(Spacer(1, 10))

    content.append(
        Paragraph("AI Scout Summary", styles["Heading2"])
    )

    content.append(
        Paragraph(scout_summary, styles["BodyText"])
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Generated by MAPLE",
            styles["Italic"]
        )
    )

    doc.build(content)

    pdf = buffer.getvalue()
    buffer.close()

    return pdf